spring.application.name=hospitalManagement

#DB configuration
spring.datasource.url=jdbc:postgresql://localhost:5432/hospitalDB
spring.datasource.username=postgres
spring.datasource.password=Sukhmeet@918
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=false

server.servlet.context-path=/hospital

#spring.security.user.name=sukh
#spring.security.user.password=pass

# if must be changed and shift to environment variables for production
jwt.secretKey=dfheo9th239fha98gre9th43iuthjk43h6jk2g6jh34g5jhg1kj34h5g1j23hg51jkh3g532j5g2ve4y45y2y6u36

# oauth 2
#spring.security.oauth2.client.registration.google.client-id=
#spring.security.oauth2.client.registration.google.client-secret=
